services:
  - type: web
    name: nyra-backend
    runtime: python
    rootDir: backend
    plan: free
    region: frankfurt
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "python manage.py migrate --noinput && gunicorn nyra.wsgi:application --bind 0.0.0.0:$PORT"
    healthCheckPath: /api/site-settings/
    envVars:
      - key: DJANGO_ENV
        value: production
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DJANGO_ALLOWED_HOSTS
        sync: false
      - key: DB_ENGINE
        value: postgres
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "5432"
      - key: IMAGEKIT_PRIVATE_KEY
        sync: false
      - key: IMAGEKIT_URL_ENDPOINT
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: JWT_COOKIE_SAMESITE
        sync: false