# Generated by Django 5.2.16 on 2026-08-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_delivery_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='commune',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('home', 'À domicile'), ('stopdesk', 'Au bureau')], default='home', help_text="Delivery method: 'home' (À domicile) or 'stopdesk' (Au bureau)", max_length=20),
        ),
    ]
