# Generated by Django 5.2.16 on 2026-08-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_order_commune_alter_order_delivery_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_image',
            field=models.ImageField(blank=True, help_text='About page image', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Homepage hero image', null=True, upload_to='site/'),
        ),
    ]
