# Generated by Django 5.2.17 on 2026-08-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_sitesettings_about_image_sitesettings_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_fr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ar',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fr',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='collection',
            name='description_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='description_fr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_ar',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_en',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_fr',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_fr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='material_ar',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='material_en',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='material_fr',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ar',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='name_fr',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
