# Generated by Django 5.2.16 on 2026-08-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_sitesettings_about_image_sitesettings_hero_image'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='store_order_status_428b25_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_at'], name='store_order_created_cad692_idx'),
        ),
    ]
