# Generated by Django 5.2.16 on 2026-08-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_store_order_status_428b25_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='free_delivery_threshold',
            field=models.PositiveIntegerField(default=7000, help_text='Minimum order subtotal for free delivery, in DA.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='free_gift_threshold',
            field=models.PositiveIntegerField(default=10000, help_text='Minimum order subtotal for free gift eligibility, in DA.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='rings_require_size',
            field=models.BooleanField(default=True, help_text='Whether ring products require the customer to select a size.'),
        ),
    ]
