# Generated by Django 5.2.17 on 2026-08-10 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_category_description_ar_category_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material_ar',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material_fr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_fr',
        ),
    ]
