# Generated by Django 5.2.16 on 2026-08-11 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_sitesettings_free_delivery_threshold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='rings_require_size',
        ),
    ]
