# Generated by Django 5.2.16 on 2026-08-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_sitesettings_rings_require_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='wilaya',
            name='idempotency_key',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
