# Generated by Django 5.2.16 on 2026-08-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_wilaya_idempotency_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wilaya',
            name='idempotency_key',
        ),
        migrations.AddField(
            model_name='order',
            name='idempotency_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='idempotency_key',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
